# Generated by Django 2.1.2 on 2018-10-18 22:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('birthdate', models.DateField()),
                ('phonenumber', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('stock', models.DecimalField(decimal_places=0, max_digits=4)),
                ('year', models.DecimalField(decimal_places=0, max_digits=4)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RentMovie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(default='n/a', max_length=200)),
                ('rent_date', models.DateField()),
                ('estimated_date', models.DateField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('returned', models.BooleanField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Client')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Movie')),
            ],
        ),
    ]
